export default {
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  SHOW_ERROR: 'SHOW_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',

  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  READ_USER_SUCCESS: 'READ_USER_SUCCESS',
  READ_USER_ONE_SUCCESS: 'READ_USER_ONE_SUCCESS',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  CLEAR_USER_ONE: 'CLEAR_USER_ONE',

  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILED: 'LOGOUT_FAILED',
}
